/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RentRouteImport } from './routes/rent'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as ApiPhotoUploadRouteImport } from './routes/api/photo-upload'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as RentIndexRouteImport } from './routes/rent.index'
import { Route as RentIdRouteImport } from './routes/rent.$id'
import { Route as RentJkSlugRouteImport } from './routes/rent.jk.$slug'
import { Route as RobotsTxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats.index'
import { Route as AuthenticatedComplexesIndexRouteImport } from './routes/_authenticated/complexes.index'
import { Route as AuthenticatedComplexesNewRouteImport } from './routes/_authenticated/complexes.new'
import { Route as AuthenticatedObjectsIndexRouteImport } from './routes/_authenticated/objects.index'
import { Route as AuthenticatedObjectsNewRouteImport } from './routes/_authenticated/objects.new'
import { Route as AuthenticatedPromoIndexRouteImport } from './routes/_authenticated/promo.index'
import { Route as AuthenticatedPromoIdRouteImport } from './routes/_authenticated/promo.$id'
import { Route as AuthenticatedPromoImportRouteImport } from './routes/_authenticated/promo.import'
import { Route as AuthenticatedSelectionsIndexRouteImport } from './routes/_authenticated/selections.index'
import { Route as AuthenticatedSocialIndexRouteImport } from './routes/_authenticated/social.index'
import { Route as AuthenticatedSystemStaffRouteImport } from './routes/_authenticated/system.staff'
import { Route as AuthenticatedSystemTelegramRouteImport } from './routes/_authenticated/system.telegram'
import { Route as AuthenticatedSystemUpdateRouteImport } from './routes/_authenticated/system.update'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedComplexesIdEditRouteImport } from './routes/_authenticated/complexes.$id.edit'
import { Route as AuthenticatedCrmClientsIndexRouteImport } from './routes/_authenticated/crm.clients.index'
import { Route as AuthenticatedCrmClientsIdRouteImport } from './routes/_authenticated/crm.clients.$id'
import { Route as AuthenticatedCrmDealsIndexRouteImport } from './routes/_authenticated/crm.deals.index'
import { Route as AuthenticatedCrmLeadsIndexRouteImport } from './routes/_authenticated/crm.leads.index'
import { Route as AuthenticatedObjectsIdIndexRouteImport } from './routes/_authenticated/objects.$id.index'
import { Route as AuthenticatedObjectsIdEditRouteImport } from './routes/_authenticated/objects.$id.edit'
import { Route as AuthenticatedObjectsIdPreviewRouteImport } from './routes/_authenticated/objects.$id.preview'
import { Route as ApiPublicCronCianSyncRouteImport } from './routes/api/public/cron/cian-sync'
import { Route as ApiPublicFeedPhotoSplatRouteImport } from './routes/api/public/feed-photo/$'
import { Route as ApiPublicFeedsCianDotxmlRouteImport } from './routes/api/public/feeds/cian[.]xml'
import { Route as ApiPublicFeedsYandexDotxmlRouteImport } from './routes/api/public/feeds/yandex[.]xml'
import { Route as ApiPublicSystemPlatformKeysRouteImport } from './routes/api/public/system/platform-keys'
import { Route as ApiPublicSystemTelegramBootstrapRouteImport } from './routes/api/public/system/telegram-bootstrap'
import { Route as ApiPublicSystemTelegramCredentialsRouteImport } from './routes/api/public/system/telegram-credentials'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPhotoUploadRoute = ApiPhotoUploadRouteImport.update({
  id: '/api/photo-upload',
  path: '/api/photo-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RentRoute,
} as any)
const RentIdRoute = RentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RentRoute,
} as any)
const RentJkSlugRoute = RentJkSlugRouteImport.update({
  id: '/jk/$slug',
  path: '/jk/$slug',
  getParentRoute: () => RentRoute,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/assistant/',
    path: '/assistant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplexesIndexRoute =
  AuthenticatedComplexesIndexRouteImport.update({
    id: '/complexes/',
    path: '/complexes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplexesNewRoute =
  AuthenticatedComplexesNewRouteImport.update({
    id: '/complexes/new',
    path: '/complexes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObjectsIndexRoute =
  AuthenticatedObjectsIndexRouteImport.update({
    id: '/objects/',
    path: '/objects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObjectsNewRoute = AuthenticatedObjectsNewRouteImport.update({
  id: '/objects/new',
  path: '/objects/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromoIndexRoute = AuthenticatedPromoIndexRouteImport.update({
  id: '/promo/',
  path: '/promo/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromoIdRoute = AuthenticatedPromoIdRouteImport.update({
  id: '/promo/$id',
  path: '/promo/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromoImportRoute =
  AuthenticatedPromoImportRouteImport.update({
    id: '/promo/import',
    path: '/promo/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSelectionsIndexRoute =
  AuthenticatedSelectionsIndexRouteImport.update({
    id: '/selections/',
    path: '/selections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocialIndexRoute = AuthenticatedSocialIndexRouteImport.update(
  {
    id: '/social/',
    path: '/social/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)
const AuthenticatedSystemStaffRoute =
  AuthenticatedSystemStaffRouteImport.update({
    id: '/system/staff',
    path: '/system/staff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemTelegramRoute =
  AuthenticatedSystemTelegramRouteImport.update({
    id: '/system/telegram',
    path: '/system/telegram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemUpdateRoute =
  AuthenticatedSystemUpdateRouteImport.update({
    id: '/system/update',
    path: '/system/update',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComplexesIdEditRoute =
  AuthenticatedComplexesIdEditRouteImport.update({
    id: '/complexes/$id/edit',
    path: '/complexes/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmClientsIndexRoute =
  AuthenticatedCrmClientsIndexRouteImport.update({
    id: '/crm/clients/',
    path: '/crm/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmClientsIdRoute =
  AuthenticatedCrmClientsIdRouteImport.update({
    id: '/crm/clients/$id',
    path: '/crm/clients/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmDealsIndexRoute =
  AuthenticatedCrmDealsIndexRouteImport.update({
    id: '/crm/deals/',
    path: '/crm/deals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmLeadsIndexRoute =
  AuthenticatedCrmLeadsIndexRouteImport.update({
    id: '/crm/leads/',
    path: '/crm/leads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObjectsIdIndexRoute =
  AuthenticatedObjectsIdIndexRouteImport.update({
    id: '/objects/$id/',
    path: '/objects/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObjectsIdEditRoute =
  AuthenticatedObjectsIdEditRouteImport.update({
    id: '/objects/$id/edit',
    path: '/objects/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObjectsIdPreviewRoute =
  AuthenticatedObjectsIdPreviewRouteImport.update({
    id: '/objects/$id/preview',
    path: '/objects/$id/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronCianSyncRoute = ApiPublicCronCianSyncRouteImport.update({
  id: '/api/public/cron/cian-sync',
  path: '/api/public/cron/cian-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedPhotoSplatRoute = ApiPublicFeedPhotoSplatRouteImport.update({
  id: '/api/public/feed-photo/$',
  path: '/api/public/feed-photo/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedsCianDotxmlRoute =
  ApiPublicFeedsCianDotxmlRouteImport.update({
    id: '/api/public/feeds/cian.xml',
    path: '/api/public/feeds/cian.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedsYandexDotxmlRoute =
  ApiPublicFeedsYandexDotxmlRouteImport.update({
    id: '/api/public/feeds/yandex.xml',
    path: '/api/public/feeds/yandex.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSystemPlatformKeysRoute =
  ApiPublicSystemPlatformKeysRouteImport.update({
    id: '/api/public/system/platform-keys',
    path: '/api/public/system/platform-keys',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSystemTelegramBootstrapRoute =
  ApiPublicSystemTelegramBootstrapRouteImport.update({
    id: '/api/public/system/telegram-bootstrap',
    path: '/api/public/system/telegram-bootstrap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSystemTelegramCredentialsRoute =
  ApiPublicSystemTelegramCredentialsRouteImport.update({
    id: '/api/public/system/telegram-credentials',
    path: '/api/public/system/telegram-credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contacts': typeof ContactsRoute
  '/management': typeof ManagementRoute
  '/privacy': typeof PrivacyRoute
  '/rent': typeof RentRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/api/photo-upload': typeof ApiPhotoUploadRoute
  '/p/$code': typeof PCodeRoute
  '/rent/$id': typeof RentIdRoute
  '/rent/jk/$slug': typeof RentJkSlugRoute
  '/rent/': typeof RentIndexRoute
  '/robots.txt': typeof RobotsTxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/complexes/new': typeof AuthenticatedComplexesNewRoute
  '/objects/new': typeof AuthenticatedObjectsNewRoute
  '/promo/$id': typeof AuthenticatedPromoIdRoute
  '/promo/import': typeof AuthenticatedPromoImportRoute
  '/system/staff': typeof AuthenticatedSystemStaffRoute
  '/system/telegram': typeof AuthenticatedSystemTelegramRoute
  '/system/update': typeof AuthenticatedSystemUpdateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/complexes/': typeof AuthenticatedComplexesIndexRoute
  '/objects/': typeof AuthenticatedObjectsIndexRoute
  '/promo/': typeof AuthenticatedPromoIndexRoute
  '/selections/': typeof AuthenticatedSelectionsIndexRoute
  '/social/': typeof AuthenticatedSocialIndexRoute
  '/complexes/$id/edit': typeof AuthenticatedComplexesIdEditRoute
  '/crm/clients/$id': typeof AuthenticatedCrmClientsIdRoute
  '/objects/$id/edit': typeof AuthenticatedObjectsIdEditRoute
  '/objects/$id/preview': typeof AuthenticatedObjectsIdPreviewRoute
  '/api/public/cron/cian-sync': typeof ApiPublicCronCianSyncRoute
  '/api/public/feed-photo/$': typeof ApiPublicFeedPhotoSplatRoute
  '/api/public/feeds/cian.xml': typeof ApiPublicFeedsCianDotxmlRoute
  '/api/public/feeds/yandex.xml': typeof ApiPublicFeedsYandexDotxmlRoute
  '/api/public/system/platform-keys': typeof ApiPublicSystemPlatformKeysRoute
  '/api/public/system/telegram-bootstrap': typeof ApiPublicSystemTelegramBootstrapRoute
  '/api/public/system/telegram-credentials': typeof ApiPublicSystemTelegramCredentialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/crm/clients/': typeof AuthenticatedCrmClientsIndexRoute
  '/crm/deals/': typeof AuthenticatedCrmDealsIndexRoute
  '/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/objects/$id/': typeof AuthenticatedObjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contacts': typeof ContactsRoute
  '/management': typeof ManagementRoute
  '/privacy': typeof PrivacyRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/api/photo-upload': typeof ApiPhotoUploadRoute
  '/p/$code': typeof PCodeRoute
  '/rent/$id': typeof RentIdRoute
  '/rent/jk/$slug': typeof RentJkSlugRoute
  '/rent': typeof RentIndexRoute
  '/robots.txt': typeof RobotsTxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/complexes/new': typeof AuthenticatedComplexesNewRoute
  '/objects/new': typeof AuthenticatedObjectsNewRoute
  '/promo/$id': typeof AuthenticatedPromoIdRoute
  '/promo/import': typeof AuthenticatedPromoImportRoute
  '/system/staff': typeof AuthenticatedSystemStaffRoute
  '/system/telegram': typeof AuthenticatedSystemTelegramRoute
  '/system/update': typeof AuthenticatedSystemUpdateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/complexes': typeof AuthenticatedComplexesIndexRoute
  '/objects': typeof AuthenticatedObjectsIndexRoute
  '/promo': typeof AuthenticatedPromoIndexRoute
  '/selections': typeof AuthenticatedSelectionsIndexRoute
  '/social': typeof AuthenticatedSocialIndexRoute
  '/complexes/$id/edit': typeof AuthenticatedComplexesIdEditRoute
  '/crm/clients/$id': typeof AuthenticatedCrmClientsIdRoute
  '/objects/$id/edit': typeof AuthenticatedObjectsIdEditRoute
  '/objects/$id/preview': typeof AuthenticatedObjectsIdPreviewRoute
  '/api/public/cron/cian-sync': typeof ApiPublicCronCianSyncRoute
  '/api/public/feed-photo/$': typeof ApiPublicFeedPhotoSplatRoute
  '/api/public/feeds/cian.xml': typeof ApiPublicFeedsCianDotxmlRoute
  '/api/public/feeds/yandex.xml': typeof ApiPublicFeedsYandexDotxmlRoute
  '/api/public/system/platform-keys': typeof ApiPublicSystemPlatformKeysRoute
  '/api/public/system/telegram-bootstrap': typeof ApiPublicSystemTelegramBootstrapRoute
  '/api/public/system/telegram-credentials': typeof ApiPublicSystemTelegramCredentialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/crm/clients': typeof AuthenticatedCrmClientsIndexRoute
  '/crm/deals': typeof AuthenticatedCrmDealsIndexRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsIndexRoute
  '/objects/$id': typeof AuthenticatedObjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contacts': typeof ContactsRoute
  '/management': typeof ManagementRoute
  '/privacy': typeof PrivacyRoute
  '/rent': typeof RentRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/api/photo-upload': typeof ApiPhotoUploadRoute
  '/p/$code': typeof PCodeRoute
  '/rent/$id': typeof RentIdRoute
  '/rent/jk/$slug': typeof RentJkSlugRoute
  '/rent/': typeof RentIndexRoute
  '/robots.txt': typeof RobotsTxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/complexes/new': typeof AuthenticatedComplexesNewRoute
  '/_authenticated/objects/new': typeof AuthenticatedObjectsNewRoute
  '/_authenticated/promo/$id': typeof AuthenticatedPromoIdRoute
  '/_authenticated/promo/import': typeof AuthenticatedPromoImportRoute
  '/_authenticated/system/staff': typeof AuthenticatedSystemStaffRoute
  '/_authenticated/system/telegram': typeof AuthenticatedSystemTelegramRoute
  '/_authenticated/system/update': typeof AuthenticatedSystemUpdateRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/complexes/': typeof AuthenticatedComplexesIndexRoute
  '/_authenticated/objects/': typeof AuthenticatedObjectsIndexRoute
  '/_authenticated/promo/': typeof AuthenticatedPromoIndexRoute
  '/_authenticated/selections/': typeof AuthenticatedSelectionsIndexRoute
  '/_authenticated/social/': typeof AuthenticatedSocialIndexRoute
  '/_authenticated/complexes/$id/edit': typeof AuthenticatedComplexesIdEditRoute
  '/_authenticated/crm/clients/$id': typeof AuthenticatedCrmClientsIdRoute
  '/_authenticated/objects/$id/edit': typeof AuthenticatedObjectsIdEditRoute
  '/_authenticated/objects/$id/preview': typeof AuthenticatedObjectsIdPreviewRoute
  '/api/public/cron/cian-sync': typeof ApiPublicCronCianSyncRoute
  '/api/public/feed-photo/$': typeof ApiPublicFeedPhotoSplatRoute
  '/api/public/feeds/cian.xml': typeof ApiPublicFeedsCianDotxmlRoute
  '/api/public/feeds/yandex.xml': typeof ApiPublicFeedsYandexDotxmlRoute
  '/api/public/system/platform-keys': typeof ApiPublicSystemPlatformKeysRoute
  '/api/public/system/telegram-bootstrap': typeof ApiPublicSystemTelegramBootstrapRoute
  '/api/public/system/telegram-credentials': typeof ApiPublicSystemTelegramCredentialsRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/_authenticated/crm/clients/': typeof AuthenticatedCrmClientsIndexRoute
  '/_authenticated/crm/deals/': typeof AuthenticatedCrmDealsIndexRoute
  '/_authenticated/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/_authenticated/objects/$id/': typeof AuthenticatedObjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contacts'
    | '/management'
    | '/privacy'
    | '/rent'
    | '/calendar'
    | '/api/photo-upload'
    | '/p/$code'
    | '/rent/$id'
    | '/rent/jk/$slug'
    | '/rent/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/complexes/new'
    | '/objects/new'
    | '/promo/$id'
    | '/promo/import'
    | '/system/staff'
    | '/system/telegram'
    | '/system/update'
    | '/api/public/health'
    | '/assistant/'
    | '/chats/'
    | '/complexes/'
    | '/objects/'
    | '/promo/'
    | '/selections/'
    | '/social/'
    | '/complexes/$id/edit'
    | '/crm/clients/$id'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/api/public/cron/cian-sync'
    | '/api/public/feed-photo/$'
    | '/api/public/feeds/cian.xml'
    | '/api/public/feeds/yandex.xml'
    | '/api/public/system/platform-keys'
    | '/api/public/system/telegram-bootstrap'
    | '/api/public/system/telegram-credentials'
    | '/api/public/telegram/webhook'
    | '/crm/clients/'
    | '/crm/deals/'
    | '/crm/leads/'
    | '/objects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contacts'
    | '/management'
    | '/privacy'
    | '/calendar'
    | '/api/photo-upload'
    | '/p/$code'
    | '/rent/$id'
    | '/rent/jk/$slug'
    | '/rent'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/complexes/new'
    | '/objects/new'
    | '/promo/$id'
    | '/promo/import'
    | '/system/staff'
    | '/system/telegram'
    | '/system/update'
    | '/api/public/health'
    | '/assistant'
    | '/chats'
    | '/complexes'
    | '/objects'
    | '/promo'
    | '/selections'
    | '/social'
    | '/complexes/$id/edit'
    | '/crm/clients/$id'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/api/public/cron/cian-sync'
    | '/api/public/feed-photo/$'
    | '/api/public/feeds/cian.xml'
    | '/api/public/feeds/yandex.xml'
    | '/api/public/system/platform-keys'
    | '/api/public/system/telegram-bootstrap'
    | '/api/public/system/telegram-credentials'
    | '/api/public/telegram/webhook'
    | '/crm/clients'
    | '/crm/deals'
    | '/crm/leads'
    | '/objects/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contacts'
    | '/management'
    | '/privacy'
    | '/rent'
    | '/_authenticated/calendar'
    | '/api/photo-upload'
    | '/p/$code'
    | '/rent/$id'
    | '/rent/jk/$slug'
    | '/rent/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/complexes/new'
    | '/_authenticated/objects/new'
    | '/_authenticated/promo/$id'
    | '/_authenticated/promo/import'
    | '/_authenticated/system/staff'
    | '/_authenticated/system/telegram'
    | '/_authenticated/system/update'
    | '/api/public/health'
    | '/_authenticated/assistant/'
    | '/_authenticated/chats/'
    | '/_authenticated/complexes/'
    | '/_authenticated/objects/'
    | '/_authenticated/promo/'
    | '/_authenticated/selections/'
    | '/_authenticated/social/'
    | '/_authenticated/complexes/$id/edit'
    | '/_authenticated/crm/clients/$id'
    | '/_authenticated/objects/$id/edit'
    | '/_authenticated/objects/$id/preview'
    | '/api/public/cron/cian-sync'
    | '/api/public/feed-photo/$'
    | '/api/public/feeds/cian.xml'
    | '/api/public/feeds/yandex.xml'
    | '/api/public/system/platform-keys'
    | '/api/public/system/telegram-bootstrap'
    | '/api/public/system/telegram-credentials'
    | '/api/public/telegram/webhook'
    | '/_authenticated/crm/clients/'
    | '/_authenticated/crm/deals/'
    | '/_authenticated/crm/leads/'
    | '/_authenticated/objects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ContactsRoute: typeof ContactsRoute
  ManagementRoute: typeof ManagementRoute
  PrivacyRoute: typeof PrivacyRoute
  RentRoute: typeof RentRouteWithChildren
  ApiPhotoUploadRoute: typeof ApiPhotoUploadRoute
  PCodeRoute: typeof PCodeRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicCronCianSyncRoute: typeof ApiPublicCronCianSyncRoute
  ApiPublicFeedPhotoSplatRoute: typeof ApiPublicFeedPhotoSplatRoute
  ApiPublicFeedsCianDotxmlRoute: typeof ApiPublicFeedsCianDotxmlRoute
  ApiPublicFeedsYandexDotxmlRoute: typeof ApiPublicFeedsYandexDotxmlRoute
  ApiPublicSystemPlatformKeysRoute: typeof ApiPublicSystemPlatformKeysRoute
  ApiPublicSystemTelegramBootstrapRoute: typeof ApiPublicSystemTelegramBootstrapRoute
  ApiPublicSystemTelegramCredentialsRoute: typeof ApiPublicSystemTelegramCredentialsRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/photo-upload': {
      id: '/api/photo-upload'
      path: '/api/photo-upload'
      fullPath: '/api/photo-upload'
      preLoaderRoute: typeof ApiPhotoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/$id': {
      id: '/rent/$id'
      path: '/$id'
      fullPath: '/rent/$id'
      preLoaderRoute: typeof RentIdRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/jk/$slug': {
      id: '/rent/jk/$slug'
      path: '/jk/$slug'
      fullPath: '/rent/jk/$slug'
      preLoaderRoute: typeof RentJkSlugRouteImport
      parentRoute: typeof RentRoute
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complexes/': {
      id: '/_authenticated/complexes/'
      path: '/complexes'
      fullPath: '/complexes/'
      preLoaderRoute: typeof AuthenticatedComplexesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complexes/new': {
      id: '/_authenticated/complexes/new'
      path: '/complexes/new'
      fullPath: '/complexes/new'
      preLoaderRoute: typeof AuthenticatedComplexesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objects/': {
      id: '/_authenticated/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof AuthenticatedObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objects/new': {
      id: '/_authenticated/objects/new'
      path: '/objects/new'
      fullPath: '/objects/new'
      preLoaderRoute: typeof AuthenticatedObjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo/': {
      id: '/_authenticated/promo/'
      path: '/promo'
      fullPath: '/promo/'
      preLoaderRoute: typeof AuthenticatedPromoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo/$id': {
      id: '/_authenticated/promo/$id'
      path: '/promo/$id'
      fullPath: '/promo/$id'
      preLoaderRoute: typeof AuthenticatedPromoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo/import': {
      id: '/_authenticated/promo/import'
      path: '/promo/import'
      fullPath: '/promo/import'
      preLoaderRoute: typeof AuthenticatedPromoImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/selections/': {
      id: '/_authenticated/selections/'
      path: '/selections'
      fullPath: '/selections/'
      preLoaderRoute: typeof AuthenticatedSelectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/': {
      id: '/_authenticated/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof AuthenticatedSocialIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/staff': {
      id: '/_authenticated/system/staff'
      path: '/system/staff'
      fullPath: '/system/staff'
      preLoaderRoute: typeof AuthenticatedSystemStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/telegram': {
      id: '/_authenticated/system/telegram'
      path: '/system/telegram'
      fullPath: '/system/telegram'
      preLoaderRoute: typeof AuthenticatedSystemTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/update': {
      id: '/_authenticated/system/update'
      path: '/system/update'
      fullPath: '/system/update'
      preLoaderRoute: typeof AuthenticatedSystemUpdateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/complexes/$id/edit': {
      id: '/_authenticated/complexes/$id/edit'
      path: '/complexes/$id/edit'
      fullPath: '/complexes/$id/edit'
      preLoaderRoute: typeof AuthenticatedComplexesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/clients/': {
      id: '/_authenticated/crm/clients/'
      path: '/crm/clients'
      fullPath: '/crm/clients/'
      preLoaderRoute: typeof AuthenticatedCrmClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/clients/$id': {
      id: '/_authenticated/crm/clients/$id'
      path: '/crm/clients/$id'
      fullPath: '/crm/clients/$id'
      preLoaderRoute: typeof AuthenticatedCrmClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/deals/': {
      id: '/_authenticated/crm/deals/'
      path: '/crm/deals'
      fullPath: '/crm/deals/'
      preLoaderRoute: typeof AuthenticatedCrmDealsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/leads/': {
      id: '/_authenticated/crm/leads/'
      path: '/crm/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objects/$id/': {
      id: '/_authenticated/objects/$id/'
      path: '/objects/$id'
      fullPath: '/objects/$id/'
      preLoaderRoute: typeof AuthenticatedObjectsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objects/$id/edit': {
      id: '/_authenticated/objects/$id/edit'
      path: '/objects/$id/edit'
      fullPath: '/objects/$id/edit'
      preLoaderRoute: typeof AuthenticatedObjectsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objects/$id/preview': {
      id: '/_authenticated/objects/$id/preview'
      path: '/objects/$id/preview'
      fullPath: '/objects/$id/preview'
      preLoaderRoute: typeof AuthenticatedObjectsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/cian-sync': {
      id: '/api/public/cron/cian-sync'
      path: '/api/public/cron/cian-sync'
      fullPath: '/api/public/cron/cian-sync'
      preLoaderRoute: typeof ApiPublicCronCianSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feed-photo/$': {
      id: '/api/public/feed-photo/$'
      path: '/api/public/feed-photo/$'
      fullPath: '/api/public/feed-photo/$'
      preLoaderRoute: typeof ApiPublicFeedPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/cian.xml': {
      id: '/api/public/feeds/cian.xml'
      path: '/api/public/feeds/cian.xml'
      fullPath: '/api/public/feeds/cian.xml'
      preLoaderRoute: typeof ApiPublicFeedsCianDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/yandex.xml': {
      id: '/api/public/feeds/yandex.xml'
      path: '/api/public/feeds/yandex.xml'
      fullPath: '/api/public/feeds/yandex.xml'
      preLoaderRoute: typeof ApiPublicFeedsYandexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/system/platform-keys': {
      id: '/api/public/system/platform-keys'
      path: '/api/public/system/platform-keys'
      fullPath: '/api/public/system/platform-keys'
      preLoaderRoute: typeof ApiPublicSystemPlatformKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/system/telegram-bootstrap': {
      id: '/api/public/system/telegram-bootstrap'
      path: '/api/public/system/telegram-bootstrap'
      fullPath: '/api/public/system/telegram-bootstrap'
      preLoaderRoute: typeof ApiPublicSystemTelegramBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/system/telegram-credentials': {
      id: '/api/public/system/telegram-credentials'
      path: '/api/public/system/telegram-credentials'
      fullPath: '/api/public/system/telegram-credentials'
      preLoaderRoute: typeof ApiPublicSystemTelegramCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedComplexesNewRoute: typeof AuthenticatedComplexesNewRoute
  AuthenticatedObjectsNewRoute: typeof AuthenticatedObjectsNewRoute
  AuthenticatedPromoIdRoute: typeof AuthenticatedPromoIdRoute
  AuthenticatedPromoImportRoute: typeof AuthenticatedPromoImportRoute
  AuthenticatedSystemStaffRoute: typeof AuthenticatedSystemStaffRoute
  AuthenticatedSystemTelegramRoute: typeof AuthenticatedSystemTelegramRoute
  AuthenticatedSystemUpdateRoute: typeof AuthenticatedSystemUpdateRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedComplexesIndexRoute: typeof AuthenticatedComplexesIndexRoute
  AuthenticatedObjectsIndexRoute: typeof AuthenticatedObjectsIndexRoute
  AuthenticatedPromoIndexRoute: typeof AuthenticatedPromoIndexRoute
  AuthenticatedSelectionsIndexRoute: typeof AuthenticatedSelectionsIndexRoute
  AuthenticatedSocialIndexRoute: typeof AuthenticatedSocialIndexRoute
  AuthenticatedComplexesIdEditRoute: typeof AuthenticatedComplexesIdEditRoute
  AuthenticatedCrmClientsIdRoute: typeof AuthenticatedCrmClientsIdRoute
  AuthenticatedObjectsIdEditRoute: typeof AuthenticatedObjectsIdEditRoute
  AuthenticatedObjectsIdPreviewRoute: typeof AuthenticatedObjectsIdPreviewRoute
  AuthenticatedCrmClientsIndexRoute: typeof AuthenticatedCrmClientsIndexRoute
  AuthenticatedCrmDealsIndexRoute: typeof AuthenticatedCrmDealsIndexRoute
  AuthenticatedCrmLeadsIndexRoute: typeof AuthenticatedCrmLeadsIndexRoute
  AuthenticatedObjectsIdIndexRoute: typeof AuthenticatedObjectsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedComplexesNewRoute: AuthenticatedComplexesNewRoute,
  AuthenticatedObjectsNewRoute: AuthenticatedObjectsNewRoute,
  AuthenticatedPromoIdRoute: AuthenticatedPromoIdRoute,
  AuthenticatedPromoImportRoute: AuthenticatedPromoImportRoute,
  AuthenticatedSystemStaffRoute: AuthenticatedSystemStaffRoute,
  AuthenticatedSystemTelegramRoute: AuthenticatedSystemTelegramRoute,
  AuthenticatedSystemUpdateRoute: AuthenticatedSystemUpdateRoute,
  AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedComplexesIndexRoute: AuthenticatedComplexesIndexRoute,
  AuthenticatedObjectsIndexRoute: AuthenticatedObjectsIndexRoute,
  AuthenticatedPromoIndexRoute: AuthenticatedPromoIndexRoute,
  AuthenticatedSelectionsIndexRoute: AuthenticatedSelectionsIndexRoute,
  AuthenticatedSocialIndexRoute: AuthenticatedSocialIndexRoute,
  AuthenticatedComplexesIdEditRoute: AuthenticatedComplexesIdEditRoute,
  AuthenticatedCrmClientsIdRoute: AuthenticatedCrmClientsIdRoute,
  AuthenticatedObjectsIdEditRoute: AuthenticatedObjectsIdEditRoute,
  AuthenticatedObjectsIdPreviewRoute: AuthenticatedObjectsIdPreviewRoute,
  AuthenticatedCrmClientsIndexRoute: AuthenticatedCrmClientsIndexRoute,
  AuthenticatedCrmDealsIndexRoute: AuthenticatedCrmDealsIndexRoute,
  AuthenticatedCrmLeadsIndexRoute: AuthenticatedCrmLeadsIndexRoute,
  AuthenticatedObjectsIdIndexRoute: AuthenticatedObjectsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RentRouteChildren {
  RentIdRoute: typeof RentIdRoute
  RentJkSlugRoute: typeof RentJkSlugRoute
  RentIndexRoute: typeof RentIndexRoute
}

const RentRouteChildren: RentRouteChildren = {
  RentIdRoute: RentIdRoute,
  RentJkSlugRoute: RentJkSlugRoute,
  RentIndexRoute: RentIndexRoute,
}

const RentRouteWithChildren = RentRoute._addFileChildren(RentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ContactsRoute: ContactsRoute,
  ManagementRoute: ManagementRoute,
  PrivacyRoute: PrivacyRoute,
  RentRoute: RentRouteWithChildren,
  ApiPhotoUploadRoute: ApiPhotoUploadRoute,
  PCodeRoute: PCodeRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicCronCianSyncRoute: ApiPublicCronCianSyncRoute,
  ApiPublicFeedPhotoSplatRoute: ApiPublicFeedPhotoSplatRoute,
  ApiPublicFeedsCianDotxmlRoute: ApiPublicFeedsCianDotxmlRoute,
  ApiPublicFeedsYandexDotxmlRoute: ApiPublicFeedsYandexDotxmlRoute,
  ApiPublicSystemPlatformKeysRoute: ApiPublicSystemPlatformKeysRoute,
  ApiPublicSystemTelegramBootstrapRoute: ApiPublicSystemTelegramBootstrapRoute,
  ApiPublicSystemTelegramCredentialsRoute:
    ApiPublicSystemTelegramCredentialsRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
