/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsNewRouteImport } from './routes/objects.new'
import { Route as ObjectsIdIndexRouteImport } from './routes/objects.$id.index'
import { Route as ObjectsIdEditRouteImport } from './routes/objects.$id.edit'
import { Route as ObjectsIdPreviewRouteImport } from './routes/objects.$id.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsNewRoute = ObjectsNewRouteImport.update({
  id: '/objects/new',
  path: '/objects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdIndexRoute = ObjectsIdIndexRouteImport.update({
  id: '/objects/$id/',
  path: '/objects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdEditRoute = ObjectsIdEditRouteImport.update({
  id: '/objects/$id/edit',
  path: '/objects/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdPreviewRoute = ObjectsIdPreviewRouteImport.update({
  id: '/objects/$id/preview',
  path: '/objects/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/objects/new': typeof ObjectsNewRoute
  '/objects/$id/edit': typeof ObjectsIdEditRoute
  '/objects/$id/preview': typeof ObjectsIdPreviewRoute
  '/objects/$id/': typeof ObjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/objects/new': typeof ObjectsNewRoute
  '/objects/$id/edit': typeof ObjectsIdEditRoute
  '/objects/$id/preview': typeof ObjectsIdPreviewRoute
  '/objects/$id': typeof ObjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/objects/new': typeof ObjectsNewRoute
  '/objects/$id/edit': typeof ObjectsIdEditRoute
  '/objects/$id/preview': typeof ObjectsIdPreviewRoute
  '/objects/$id/': typeof ObjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/objects/new'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/objects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/objects/new'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/objects/$id'
  id:
    | '__root__'
    | '/'
    | '/objects/new'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/objects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObjectsNewRoute: typeof ObjectsNewRoute
  ObjectsIdEditRoute: typeof ObjectsIdEditRoute
  ObjectsIdPreviewRoute: typeof ObjectsIdPreviewRoute
  ObjectsIdIndexRoute: typeof ObjectsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/new': {
      id: '/objects/new'
      path: '/objects/new'
      fullPath: '/objects/new'
      preLoaderRoute: typeof ObjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id/': {
      id: '/objects/$id/'
      path: '/objects/$id'
      fullPath: '/objects/$id/'
      preLoaderRoute: typeof ObjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id/edit': {
      id: '/objects/$id/edit'
      path: '/objects/$id/edit'
      fullPath: '/objects/$id/edit'
      preLoaderRoute: typeof ObjectsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id/preview': {
      id: '/objects/$id/preview'
      path: '/objects/$id/preview'
      fullPath: '/objects/$id/preview'
      preLoaderRoute: typeof ObjectsIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObjectsNewRoute: ObjectsNewRoute,
  ObjectsIdEditRoute: ObjectsIdEditRoute,
  ObjectsIdPreviewRoute: ObjectsIdPreviewRoute,
  ObjectsIdIndexRoute: ObjectsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
