/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RentRouteImport } from './routes/rent'
import { Route as ComplexesIndexRouteImport } from './routes/complexes.index'
import { Route as ComplexesNewRouteImport } from './routes/complexes.new'
import { Route as ObjectsIndexRouteImport } from './routes/objects.index'
import { Route as ObjectsNewRouteImport } from './routes/objects.new'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as RentIndexRouteImport } from './routes/rent.index'
import { Route as RentIdRouteImport } from './routes/rent.$id'
import { Route as SelectionsIndexRouteImport } from './routes/selections.index'
import { Route as ComplexesIdEditRouteImport } from './routes/complexes.$id.edit'
import { Route as CrmClientsIndexRouteImport } from './routes/crm.clients.index'
import { Route as CrmClientsIdRouteImport } from './routes/crm.clients.$id'
import { Route as CrmLeadsIndexRouteImport } from './routes/crm.leads.index'
import { Route as ObjectsIdIndexRouteImport } from './routes/objects.$id.index'
import { Route as ObjectsIdEditRouteImport } from './routes/objects.$id.edit'
import { Route as ObjectsIdPreviewRouteImport } from './routes/objects.$id.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexesIndexRoute = ComplexesIndexRouteImport.update({
  id: '/complexes/',
  path: '/complexes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexesNewRoute = ComplexesNewRouteImport.update({
  id: '/complexes/new',
  path: '/complexes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIndexRoute = ObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsNewRoute = ObjectsNewRouteImport.update({
  id: '/objects/new',
  path: '/objects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RentRoute,
} as any)
const RentIdRoute = RentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RentRoute,
} as any)
const SelectionsIndexRoute = SelectionsIndexRouteImport.update({
  id: '/selections/',
  path: '/selections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexesIdEditRoute = ComplexesIdEditRouteImport.update({
  id: '/complexes/$id/edit',
  path: '/complexes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClientsIndexRoute = CrmClientsIndexRouteImport.update({
  id: '/crm/clients/',
  path: '/crm/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClientsIdRoute = CrmClientsIdRouteImport.update({
  id: '/crm/clients/$id',
  path: '/crm/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsIndexRoute = CrmLeadsIndexRouteImport.update({
  id: '/crm/leads/',
  path: '/crm/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdIndexRoute = ObjectsIdIndexRouteImport.update({
  id: '/objects/$id/',
  path: '/objects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdEditRoute = ObjectsIdEditRouteImport.update({
  id: '/objects/$id/edit',
  path: '/objects/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdPreviewRoute = ObjectsIdPreviewRouteImport.update({
  id: '/objects/$id/preview',
  path: '/objects/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/management': typeof ManagementRoute
  '/privacy': typeof PrivacyRoute
  '/rent': typeof RentRouteWithChildren
  '/complexes/new': typeof ComplexesNewRoute
  '/objects/new': typeof ObjectsNewRoute
  '/p/$code': typeof PCodeRoute
  '/rent/$id': typeof RentIdRoute
  '/complexes/': typeof ComplexesIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/rent/': typeof RentIndexRoute
  '/selections/': typeof SelectionsIndexRoute
  '/complexes/$id/edit': typeof ComplexesIdEditRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/objects/$id/edit': typeof ObjectsIdEditRoute
  '/objects/$id/preview': typeof ObjectsIdPreviewRoute
  '/crm/clients/': typeof CrmClientsIndexRoute
  '/crm/leads/': typeof CrmLeadsIndexRoute
  '/objects/$id/': typeof ObjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/management': typeof ManagementRoute
  '/privacy': typeof PrivacyRoute
  '/complexes/new': typeof ComplexesNewRoute
  '/objects/new': typeof ObjectsNewRoute
  '/p/$code': typeof PCodeRoute
  '/rent/$id': typeof RentIdRoute
  '/complexes': typeof ComplexesIndexRoute
  '/objects': typeof ObjectsIndexRoute
  '/rent': typeof RentIndexRoute
  '/selections': typeof SelectionsIndexRoute
  '/complexes/$id/edit': typeof ComplexesIdEditRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/objects/$id/edit': typeof ObjectsIdEditRoute
  '/objects/$id/preview': typeof ObjectsIdPreviewRoute
  '/crm/clients': typeof CrmClientsIndexRoute
  '/crm/leads': typeof CrmLeadsIndexRoute
  '/objects/$id': typeof ObjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/calendar': typeof CalendarRoute
  '/contacts': typeof ContactsRoute
  '/management': typeof ManagementRoute
  '/privacy': typeof PrivacyRoute
  '/rent': typeof RentRouteWithChildren
  '/complexes/new': typeof ComplexesNewRoute
  '/objects/new': typeof ObjectsNewRoute
  '/p/$code': typeof PCodeRoute
  '/rent/$id': typeof RentIdRoute
  '/complexes/': typeof ComplexesIndexRoute
  '/objects/': typeof ObjectsIndexRoute
  '/rent/': typeof RentIndexRoute
  '/selections/': typeof SelectionsIndexRoute
  '/complexes/$id/edit': typeof ComplexesIdEditRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/objects/$id/edit': typeof ObjectsIdEditRoute
  '/objects/$id/preview': typeof ObjectsIdPreviewRoute
  '/crm/clients/': typeof CrmClientsIndexRoute
  '/crm/leads/': typeof CrmLeadsIndexRoute
  '/objects/$id/': typeof ObjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/calendar'
    | '/contacts'
    | '/management'
    | '/privacy'
    | '/rent'
    | '/complexes/new'
    | '/objects/new'
    | '/p/$code'
    | '/rent/$id'
    | '/complexes/'
    | '/objects/'
    | '/rent/'
    | '/selections/'
    | '/complexes/$id/edit'
    | '/crm/clients/$id'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/crm/clients/'
    | '/crm/leads/'
    | '/objects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/calendar'
    | '/contacts'
    | '/management'
    | '/privacy'
    | '/complexes/new'
    | '/objects/new'
    | '/p/$code'
    | '/rent/$id'
    | '/complexes'
    | '/objects'
    | '/rent'
    | '/selections'
    | '/complexes/$id/edit'
    | '/crm/clients/$id'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/crm/clients'
    | '/crm/leads'
    | '/objects/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/calendar'
    | '/contacts'
    | '/management'
    | '/privacy'
    | '/rent'
    | '/complexes/new'
    | '/objects/new'
    | '/p/$code'
    | '/rent/$id'
    | '/complexes/'
    | '/objects/'
    | '/rent/'
    | '/selections/'
    | '/complexes/$id/edit'
    | '/crm/clients/$id'
    | '/objects/$id/edit'
    | '/objects/$id/preview'
    | '/crm/clients/'
    | '/crm/leads/'
    | '/objects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CalendarRoute: typeof CalendarRoute
  ContactsRoute: typeof ContactsRoute
  ManagementRoute: typeof ManagementRoute
  PrivacyRoute: typeof PrivacyRoute
  RentRoute: typeof RentRouteWithChildren
  ComplexesNewRoute: typeof ComplexesNewRoute
  ObjectsNewRoute: typeof ObjectsNewRoute
  PCodeRoute: typeof PCodeRoute
  ComplexesIndexRoute: typeof ComplexesIndexRoute
  ObjectsIndexRoute: typeof ObjectsIndexRoute
  SelectionsIndexRoute: typeof SelectionsIndexRoute
  ComplexesIdEditRoute: typeof ComplexesIdEditRoute
  CrmClientsIdRoute: typeof CrmClientsIdRoute
  ObjectsIdEditRoute: typeof ObjectsIdEditRoute
  ObjectsIdPreviewRoute: typeof ObjectsIdPreviewRoute
  CrmClientsIndexRoute: typeof CrmClientsIndexRoute
  CrmLeadsIndexRoute: typeof CrmLeadsIndexRoute
  ObjectsIdIndexRoute: typeof ObjectsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexes/': {
      id: '/complexes/'
      path: '/complexes'
      fullPath: '/complexes/'
      preLoaderRoute: typeof ComplexesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexes/new': {
      id: '/complexes/new'
      path: '/complexes/new'
      fullPath: '/complexes/new'
      preLoaderRoute: typeof ComplexesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/': {
      id: '/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof ObjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/new': {
      id: '/objects/new'
      path: '/objects/new'
      fullPath: '/objects/new'
      preLoaderRoute: typeof ObjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof RentRoute
    }
    '/rent/$id': {
      id: '/rent/$id'
      path: '/$id'
      fullPath: '/rent/$id'
      preLoaderRoute: typeof RentIdRouteImport
      parentRoute: typeof RentRoute
    }
    '/selections/': {
      id: '/selections/'
      path: '/selections'
      fullPath: '/selections/'
      preLoaderRoute: typeof SelectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexes/$id/edit': {
      id: '/complexes/$id/edit'
      path: '/complexes/$id/edit'
      fullPath: '/complexes/$id/edit'
      preLoaderRoute: typeof ComplexesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/clients/': {
      id: '/crm/clients/'
      path: '/crm/clients'
      fullPath: '/crm/clients/'
      preLoaderRoute: typeof CrmClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/clients/$id': {
      id: '/crm/clients/$id'
      path: '/crm/clients/$id'
      fullPath: '/crm/clients/$id'
      preLoaderRoute: typeof CrmClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads/': {
      id: '/crm/leads/'
      path: '/crm/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof CrmLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id/': {
      id: '/objects/$id/'
      path: '/objects/$id'
      fullPath: '/objects/$id/'
      preLoaderRoute: typeof ObjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id/edit': {
      id: '/objects/$id/edit'
      path: '/objects/$id/edit'
      fullPath: '/objects/$id/edit'
      preLoaderRoute: typeof ObjectsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id/preview': {
      id: '/objects/$id/preview'
      path: '/objects/$id/preview'
      fullPath: '/objects/$id/preview'
      preLoaderRoute: typeof ObjectsIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RentRouteChildren {
  RentIdRoute: typeof RentIdRoute
  RentIndexRoute: typeof RentIndexRoute
}

const RentRouteChildren: RentRouteChildren = {
  RentIdRoute: RentIdRoute,
  RentIndexRoute: RentIndexRoute,
}

const RentRouteWithChildren = RentRoute._addFileChildren(RentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CalendarRoute: CalendarRoute,
  ContactsRoute: ContactsRoute,
  ManagementRoute: ManagementRoute,
  PrivacyRoute: PrivacyRoute,
  RentRoute: RentRouteWithChildren,
  ComplexesNewRoute: ComplexesNewRoute,
  ObjectsNewRoute: ObjectsNewRoute,
  PCodeRoute: PCodeRoute,
  ComplexesIndexRoute: ComplexesIndexRoute,
  ObjectsIndexRoute: ObjectsIndexRoute,
  SelectionsIndexRoute: SelectionsIndexRoute,
  ComplexesIdEditRoute: ComplexesIdEditRoute,
  CrmClientsIdRoute: CrmClientsIdRoute,
  ObjectsIdEditRoute: ObjectsIdEditRoute,
  ObjectsIdPreviewRoute: ObjectsIdPreviewRoute,
  CrmClientsIndexRoute: CrmClientsIndexRoute,
  CrmLeadsIndexRoute: CrmLeadsIndexRoute,
  ObjectsIdIndexRoute: ObjectsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
