CREATE TYPE public.property_type AS ENUM ('apartment','aparts','house','villa','townhouse');
CREATE TYPE public.property_status AS ENUM ('free','rented','booked','archived');

CREATE TABLE public.properties (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ref_id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) NOT NULL UNIQUE,
  title text NOT NULL,
  type public.property_type NOT NULL DEFAULT 'apartment',
  complex_name text NOT NULL DEFAULT '',
  complex_id uuid,
  floor integer,
  total_floors integer,
  rooms integer NOT NULL DEFAULT 1,
  bathrooms integer NOT NULL DEFAULT 1,
  status public.property_status NOT NULL DEFAULT 'free',
  description text NOT NULL DEFAULT '',
  photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.properties TO anon, authenticated;
GRANT ALL ON public.properties TO service_role;

ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Properties are readable by app users" ON public.properties FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Properties are insertable by app users" ON public.properties FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Properties are updatable by app users" ON public.properties FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER properties_set_updated_at
BEFORE UPDATE ON public.properties
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE POLICY "Property photos readable" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'property-photos');
CREATE POLICY "Property photos uploadable" ON storage.objects FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'property-photos');
CREATE POLICY "Property photos updatable" ON storage.objects FOR UPDATE TO anon, authenticated USING (bucket_id = 'property-photos') WITH CHECK (bucket_id = 'property-photos');
CREATE POLICY "Property photos deletable" ON storage.objects FOR DELETE TO anon, authenticated USING (bucket_id = 'property-photos');

INSERT INTO public.properties (ref_id, title, type, complex_name, floor, total_floors, rooms, bathrooms, status, description, photos) VALUES
(1023, 'Квартира в ЖК Кислород', 'apartment', 'ЖК Кислород', 7, 18, 2, 2, 'free', 'Светлая двухкомнатная квартира с панорамными окнами и качественным ремонтом.', '[{"path":"demo/p1.jpg"}]'::jsonb),
(1022, 'Апартаменты в Морской Симфонии', 'aparts', 'Морская Симфония', 12, 21, 1, 1, 'rented', 'Апартаменты с видом на море, полностью меблированы.', '[{"path":"demo/p2.jpg"}]'::jsonb),
(1021, 'Вилла у моря', 'villa', 'Романово', 2, 2, 6, 4, 'booked', 'Просторная вилла с бассейном и собственным участком у моря.', '[{"path":"demo/p3.jpg"}]'::jsonb),
(1020, 'Таунхаус', 'townhouse', 'Олимпийский', 1, 3, 3, 2, 'archived', 'Таунхаус в закрытом квартале рядом с парком.', '[{"path":"demo/p4.jpg"}]'::jsonb);

SELECT setval(pg_get_serial_sequence('public.properties','ref_id'), 1024, false);